In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("heart__missing.csv")

In [ ]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52.0,1.0,0.0,125.0,212.0,0.0,1.0,168.0,0.0,1.0,2.0,2.0,3.0,0
1,53.0,NaN,0.0,140.0,203.0,NaN,NaN,155.0,1.0,3.1,0.0,0.0,3.0,0
2,NaN,1.0,0.0,145.0,174.0,0.0,1.0,125.0,1.0,NaN,0.0,NaN,3.0,0
3,61.0,1.0,0.0,148.0,203.0,0.0,1.0,NaN,0.0,0.0,2.0,1.0,3.0,0
4,62.0,0.0,NaN,NaN,NaN,1.0,1.0,106.0,0.0,NaN,1.0,3.0,2.0,0

In [ ]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59.0,1.0,1.0,140.0,221.0,0.0,1.0,164.0,1.0,0.0,2.0,NaN,2.0,1
1021,60.0,1.0,0.0,125.0,258.0,0.0,0.0,141.0,1.0,NaN,1.0,1.0,3.0,0
1022,47.0,1.0,NaN,NaN,275.0,0.0,0.0,NaN,1.0,NaN,NaN,1.0,2.0,0
1023,50.0,0.0,0.0,110.0,254.0,0.0,NaN,159.0,0.0,0.0,2.0,0.0,2.0,1
1024,54.0,1.0,0.0,120.0,188.0,0.0,1.0,113.0,0.0,1.4,1.0,1.0,NaN,0

In [ ]:
df.isna().sum()

age         156
sex         144
cp          183
trestbps    145
chol        150
fbs         156
restecg     148
thalach     143
exang       163
oldpeak     159
slope       154
ca          150
thal        148
target        0
dtype: int64

In [ ]:
cate=["age","trestbps","chol","thalach","oldpeak","ca"]

In [ ]:
for  i  in cate:
    df[i]=df[i].fillna(df[i].mean())

In [ ]:
nzt=["sex","fbs","cp","restecg","exang","slope","thal"]
for i in nzt:
    df[i]=df[i].fillna(df[i].mode()[0])

In [ ]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='str')

In [ ]:
df.duplicated

<bound method DataFrame.duplicated of             age  sex   cp    trestbps        chol  fbs  restecg     thalach  \
0     52.000000  1.0  0.0  125.000000  212.000000  0.0      1.0  168.000000
1     53.000000  1.0  0.0  140.000000  203.000000  0.0      1.0  155.000000
2     54.332566  1.0  0.0  145.000000  174.000000  0.0      1.0  125.000000
3     61.000000  1.0  0.0  148.000000  203.000000  0.0      1.0  148.768707
4     62.000000  0.0  0.0  131.423864  247.340571  1.0      1.0  106.000000
...         ...  ...  ...         ...         ...  ...      ...         ...
1020  59.000000  1.0  1.0  140.000000  221.000000  0.0      1.0  164.000000
1021  60.000000  1.0  0.0  125.000000  258.000000  0.0      0.0  141.000000
1022  47.000000  1.0  0.0  131.423864  275.000000  0.0      0.0  148.768707
1023  50.000000  0.0  0.0  110.000000  254.000000  0.0      1.0  159.000000
1024  54.000000  1.0  0.0  120.000000  188.000000  0.0      1.0  113.000000

      exang   oldpeak  slope        ca  thal  target
0       0.0  1.000000    2.0  2.000000   3.0       0
1       1.0  3.100000    0.0  0.000000   3.0       0
2       1.0  1.081986    0.0  0.721143   3.0       0
3       0.0  0.000000    2.0  1.000000   3.0       0
4       0.0  1.081986    1.0  3.000000   2.0       0
...     ...       ...    ...       ...   ...     ...
1020    1.0  0.000000    2.0  0.721143   2.0       1
1021    1.0  1.081986    1.0  1.000000   3.0       0
1022    1.0  1.081986    1.0  1.000000   2.0       0
1023    0.0  0.000000    2.0  0.000000   2.0       1
1024    0.0  1.400000    1.0  1.000000   2.0       0

[1025 rows x 14 columns]>

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
x = df.drop(columns="target")
y= df["target"]
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 948, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.30,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

knn=KNeighborsClassifier(n_neighbors=5)
svm=SVC()
naive=GaussianNB()

In [ ]:
lst=[knn,svm,naive]

for i in lst:
    print("model selection______________",i)
    print(i.fit(x_train,y_train))
    y_pred=i.predict(x_test)

    print("confusion matrix______________",i)
    print(confusion_matrix(y_pred,y_test))

    print("accuracy score________________",i)
    print(accuracy_score(y_pred,y_test))

model selection______________ KNeighborsClassifier()
KNeighborsClassifier()
confusion matrix______________ KNeighborsClassifier()
[[116  12]
 [ 23 134]]
accuracy score________________ KNeighborsClassifier()
0.8771929824561403
model selection______________ SVC()
SVC()
confusion matrix______________ SVC()
[[109  15]
 [ 30 131]]
accuracy score________________ SVC()
0.8421052631578947
model selection______________ GaussianNB()
GaussianNB()
confusion matrix______________ GaussianNB()
[[103  25]
 [ 36 121]]
accuracy score________________ GaussianNB()
0.7859649122807018

In [ ]:
from sklearn.metrics import classification_report
cr=classification_report(y_pred,y_test)
print(cr)