In [268]:
import pandas as pd
import matplotlib.pyplot as plt

In [269]:
df=pd.read_csv("Stars.csv")

In [270]:
df.head()

   Temperature         L       R    A_M Color Spectral_Class  Type
0         3068  0.002400  0.1700  16.12   Red              M     0
1         3042  0.000500  0.1542  16.60   Red              M     0
2         2600  0.000300  0.1020  18.70   Red              M     0
3         2800  0.000200  0.1600  16.65   Red              M     0
4         1939  0.000138  0.1030  20.06   Red              M     0

In [271]:
df.tail()

     Temperature         L       R    A_M  Color Spectral_Class  Type
235        38940  374830.0  1356.0  -9.93   Blue              O     5
236        30839  834042.0  1194.0 -10.63   Blue              O     5
237         8829  537493.0  1423.0 -10.73  White              A     5
238         9235  404940.0  1112.0 -11.23  White              A     5
239        37882  294903.0  1783.0  -7.80   Blue              O     5

In [272]:
df.isna().sum()

Temperature       0
L                 0
R                 0
A_M               0
Color             0
Spectral_Class    0
Type              0
dtype: int64

In [273]:
df.shape

(240, 7)

In [287]:
df["Type"].unique()

array([0, 1, 2, 3, 4, 5])

In [288]:
df.dtypes

Temperature         int64
L                 float64
R                 float64
A_M               float64
Color               int64
Spectral_Class      int64
Type                int64
dtype: object

In [289]:
from sklearn.preprocessing import LabelEncoder

In [290]:
le=LabelEncoder()

In [291]:
df["Color"]=le.fit_transform(df["Color"])
df["Spectral_Class"]=le.fit_transform(df["Spectral_Class"])

In [292]:
x=df.drop(columns="Type")
y=df["Type"]

In [293]:
x

     Temperature              L          R    A_M  Color  Spectral_Class
0           3068       0.002400     0.1700  16.12      8               5
1           3042       0.000500     0.1542  16.60      8               5
2           2600       0.000300     0.1020  18.70      8               5
3           2800       0.000200     0.1600  16.65      8               5
4           1939       0.000138     0.1030  20.06      8               5
..           ...            ...        ...    ...    ...             ...
235        38940  374830.000000  1356.0000  -9.93      0               6
236        30839  834042.000000  1194.0000 -10.63      0               6
237         8829  537493.000000  1423.0000 -10.73      9               0
238         9235  404940.000000  1112.0000 -11.23      9               0
239        37882  294903.000000  1783.0000  -7.80      0               6

[240 rows x 6 columns]

In [294]:
from sklearn.model_selection import train_test_split

In [295]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=42)

In [296]:
from sklearn.preprocessing import StandardScaler

In [297]:
scaler=StandardScaler()

In [298]:
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)

In [299]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import  confusion_matrix
from sklearn.metrics import accuracy_score

knn=KNeighborsClassifier(n_neighbors=7)
svm=SVC()
lst=[knn,svm]

In [300]:
for i in lst:
    print("model selection_______________",i)
    print(i.fit(x_train,y_train))
    y_pred=i.predict(x_test)


    print("confusion_matrix__________",)
    print(confusion_matrix(y_pred,y_test))


    print("accuracy_score____________",)
    print(accuracy_score(y_pred,y_test))

model selection_______________ KNeighborsClassifier(n_neighbors=7)
KNeighborsClassifier(n_neighbors=7)
confusion_matrix__________
[[10  0  0  0  0  0]
 [ 0 11  0  1  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  8  1  0]
 [ 0  0  0  0  8  1]
 [ 0  0  0  0  0 11]]
accuracy_score____________
0.95
model selection_______________ SVC()
SVC()
confusion_matrix__________
[[10  1  0  0  0  0]
 [ 0 10  0  1  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0  9  0]
 [ 0  0  0  0  0 12]]
accuracy_score____________
0.9666666666666667